### ISSUE TITLE
Algoritmo de Dijkstra

### ISSUE THREAD

**Issue by KlebsonFerreira** [KlebsonFerreira/Projetocconoitefg.esy.es#3]
O Codigo não esta entregando o menor custo.

// Method of Dijkstra
	this.start = function() {
		canvas.addEventListener('mousedown',function(evt) {
			var mousePos = getMousePos(canvas,evt);
			mouseDown(canvas,mousePos.x,mousePos.y);
		},false);
	}

	//
	//  Node Extensão para Algoritmo de Dijkstra
	//
	function extNode(node) {
		// extends Node Properties
		node.dist = -1;			// Distância do começo node
		node.prev = -1;			// node anterior no caminho mais curto
		node.stat = STAT.oth;		// Se fix, sel, adj, or oth
		node.labelPos = {dx:0, dy:0};	// Onde mostrar o rótulo
	}
	// Extensão Node Metódos Pintar 
	Node.prototype.paint = function(context,node) {	// sobrepor Node.paint
		if (node.stat==STAT.fix) {		// Fixo
			context.strokeStyle = 'blue';
			context.fillStyle = 'cyan';
		} else if (node.stat==STAT.sel) {	// Selecionado
			context.strokeStyle = 'blue';
			context.fillStyle = 'pink';
		} else if (node.stat==STAT.adj) {	// Adjacente
			context.strokeStyle = 'red';
			context.fillStyle = 'yellow';
		} else {				// Outros
			context.strokeStyle = 'black';
			context.fillStyle = 'white';
		}
		node.drawNode(context,node);
		printLabel(context,node);
	
		// Função local
		function printLabel(context,node) {	// Pintar valores
			var s;
			if (node.dist<0) {
				s = "";
			} else {
				var s = ""+node.dist;
			}
			var w1 = context.measureText(s).width+node.wh.h/5;
			var x1 = node.xy.x+(node.wh.w/2+node.wh.h/2)*node.labelPos.dx;
			var y1 = node.xy.y+(node.wh.h+1)*node.labelPos.dy;
			if ((node.stat==STAT.sel)||(node.stat==STAT.fix)) {
							// Se selecionado ou Fixo
				context.fillStyle = 'blue';
			} else if (node.stat==STAT.adj) {	// adjacent
				context.fillStyle = 'red';
			}
			context.fillText(s,x1,y1+node.wh.h/5);
		}	// Final do Método para pintar valores
	}
	Node.prototype.setlabelPos = function() {
		// Encontrar direção esparsa
		// Não chamar antes de bordas são registradas
		var x0 = [ 1,  0, -1,  1,  0, -1];
		var y0 = [ 1,  1,  1, -1, -1, -1];
		var m0 = y0.length;
		var k=0;
		var w=weight(this.num,x0[0],y0[0]);
		for (var j=1; j<m0; j++) {
			var z = weight(this.num,x0[j],y0[j]);
			if (z<w) {
				w = z;
				k = j;
			}
		}
		this.labelPos = {dx:x0[k], dy: y0[k]};

**Comment by DaviAdelino** [comment]
Resolvido:

// Method of Dijkstra
this.start = function() {
canvas.addEventListener('mousedown',function(evt) {
var mousePos = getMousePos(canvas,evt);
mouseDown(canvas,mousePos.x,mousePos.y);
},false);
}

//
//  Node Extensão para Algoritmo de Dijkstra
//
function extNode(node) {
	// extends Node Properties
	node.dist = -1;			// Distância do começo node
	node.prev = -1;			// node anterior no caminho mais curto
	node.stat = STAT.oth;		// Se fix, sel, adj, or oth
	node.labelPos = {dx:0, dy:0};	// Onde mostrar o rótulo
}
// Extensão Node Metódos Pintar 
Node.prototype.paint = function(context,node) {	// sobrepor Node.paint
	if (node.stat==STAT.fix) {		// Fixo
		context.strokeStyle = 'blue';
		context.fillStyle = 'cyan';
	} else if (node.stat==STAT.sel) {	// Selecionado
		context.strokeStyle = 'blue';
		context.fillStyle = 'pink';
	} else if (node.stat==STAT.adj) {	// Adjacente
		context.strokeStyle = 'red';
		context.fillStyle = 'yellow';
	} else {				// Outros
		context.strokeStyle = 'black';
		context.fillStyle = 'white';
	}
	node.drawNode(context,node);
	printLabel(context,node);

	// Função local
	function printLabel(context,node) {	// Pintar valores
		var s;
		if (node.dist<0) {
			s = "";
		} else {
			var s = ""+node.dist;
		}
		var w1 = context.measureText(s).width+node.wh.h/5;
		var x1 = node.xy.x+(node.wh.w/2+node.wh.h/2)*node.labelPos.dx;
		var y1 = node.xy.y+(node.wh.h+1)*node.labelPos.dy;
		if ((node.stat==STAT.sel)||(node.stat==STAT.fix)) {
						// Se selecionado ou Fixo
			context.fillStyle = 'blue';
		} else if (node.stat==STAT.adj) {	// adjacent
			context.fillStyle = 'red';
		}
		context.fillText(s,x1,y1+node.wh.h/5);
	}	// Final do Método para pintar valores
}
Node.prototype.setlabelPos = function() {
	// Encontrar direção esparsa
	// Não chamar antes de bordas são registradas
	var x0 = [ 1,  0, -1,  1,  0, -1];
	var y0 = [ 1,  1,  1, -1, -1, -1];
	var m0 = y0.length;
	var k=0;
	var w=weight(this.num,x0[0],y0[0]);
	for (var j=1; j<m0; j++) {
		var z = weight(this.num,x0[j],y0[j]);
		if (z<w) {
			w = z;
			k = j;
		}
	}
	this.labelPos = {dx:x0[k], dy: y0[k]};
